// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWithModel'](arg1, arg2, arg3);
}

export function GetModelConfig(arg1, arg2) {
  return window['go']['main']['App']['GetModelConfig'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveModelConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveModelConfig'](arg1, arg2, arg3);
}

export function ScanLocalModels(arg1) {
  return window['go']['main']['App']['ScanLocalModels'](arg1);
}
