// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {connectors} from '../models';

export function ChatWithModel(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAuthToken():Promise<string>;

export function GetModelConfig(arg1:string,arg2:string):Promise<main.ModelConfig>;

export function SaveModelConfig(arg1:string,arg2:string,arg3:main.ModelConfig):Promise<string>;

export function ScanLocalModels(arg1:string):Promise<connectors.ScanResult>;

export function SetAuthToken(arg1:string):Promise<void>;

export function StartLogin():Promise<void>;
